variable "cluster_name" {}
variable "region" {}
variable "network" {}
variable "subnet" {}
variable "sa_email" {}
variable "machine_type" {}
variable "min_nodes" {}
variable "max_nodes" {}
variable "secondary_machine_type" {}
variable "secondary_min_nodes" {}
variable "secondary_max_nodes" {}